compressionLevel: mixed

enableGlobalCache: true

nodeLinker: pnp

packageExtensions:
  "@storybook/core-common@*":
    dependencies:
      "@storybook/nextjs": "*"
  "@storybook/nextjs@*":
    dependencies:
      webpack: "*"

yarnPath: .yarn/releases/yarn-4.1.1.cjs
